=== Eslam-Abdelaziz/Attendance_Management_system/Attendance Management System/Data/users_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:simpleType name="NameType">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:pattern value="[A-Za-z ]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EmailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PassType">
        <xs:restriction base="xs:string">
            <xs:minLength value="6"/>
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Name" type="NameType"/>
    <xs:element name="ID" type="xs:integer"/>
    <xs:element name="Email" type="EmailType"/>
    <xs:element name="Password" type="PassType"/>
    <xs:element name="Class" type="xs:string"/>

    <xs:group name="userGroup">
        <xs:sequence>
            <xs:element ref="Name"/>
            <xs:element ref="ID"/>
            <xs:element ref="Email"/>
            <xs:element ref="Password"/>
            <xs:element ref="Class" minOccurs="0"/>
        </xs:sequence>
    </xs:group>
	

    <xs:complexType name="AdminComplex">
        <xs:group ref="userGroup"/>
    </xs:complexType>

    <xs:complexType name="TeacherComplex">
        <xs:group ref="userGroup"/>
    </xs:complexType>

    <xs:complexType name="StudentComplex">
        <xs:group ref="userGroup"/>
    </xs:complexType>

    <xs:element name="Admin" type="AdminComplex"/>
    <xs:element name="Teacher" type="TeacherComplex"/>
    <xs:element name="Student" type="StudentComplex"/>

    <xs:complexType name="UsersComplex">
        <xs:sequence>
            <xs:element ref="Admin"/>
            <xs:element ref="Teacher" maxOccurs="unbounded"/>
            <xs:element ref="Student" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Users" type="UsersComplex"/>

</xs:schema>

=== Eslam-Abdelaziz/Attendance_Management_system/Attendance Management System/Data/users.xml
<?xml version="1.0" encoding="utf-8"?>
<Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users_schema.xsd">
  <Admin>
    <Name>Admin User</Name>
    <ID>123</ID>
    <Email>admin@example.com</Email>
    <Password>adminpass</Password>
  </Admin>
  <Teacher>
    <Name>John Smith</Name>
    <ID>456</ID>
    <Email>john.smith@example.com</Email>
    <Password>teacherpass</Password>
    <Class>Math101</Class>
  </Teacher>
  <Teacher>
    <Name>Sarah Johnson</Name>
    <ID>789</ID>
    <Email>sarah.johnson@example.com</Email>
    <Password>teacherpass</Password>
    <Class>English101</Class>
  </Teacher>
  <Student>
    <Name>Emma Watson</Name>
    <ID>101</ID>
    <Email>emma.watson@example.com</Email>
    <Password>studentpass</Password>
    <Class>Math101</Class>
  </Student>
  <Student>
    <Name>Michael Brown</Name>
    <ID>102</ID>
    <Email>michael.brown@example.com</Email>
    <Password>studentpass</Password>
    <Class>English101</Class>
  </Student>
  <Student>
    <Name>New Student</Name>
    <ID>103</ID>
    <Email>new.student@example.com</Email>
    <Password>newstudentpass</Password>
    <Class>Science101</Class>
  </Student>
  <Student>
    <Name>Ahmed</Name>
    <ID>12</ID>
    <Email>Ahmed@msmail.com</Email>
    <Password>12345Test</Password>
    <Class>Science101</Class>
  </Student>
  <Student>
    <Name>Ahmed</Name>
    <ID>120</ID>
    <Email>MahmoudAhmed@gmail.com</Email>
    <Password>amknfnk9827</Password>
    <Class>Science101</Class>
  </Student>
  <Student>
    <Name>King</Name>
    <ID>99</ID>
    <Email>King@gmail.com</Email>
    <Password>123iudmks</Password>
    <Class>Science101</Class>
  </Student>
</Users>
